---
title: "Lab 6"
author: "Rahmat Ashari"
date: " `r format(Sys.time(), format = '%b %d, %Y')` "
output: 
  html_document:
    toc: yes
    toc_float: yes
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```


# Task 1
```{r}

getwd()

```

# Task Trial
```{r}

curve(dnorm(x, mean = 10, sd = 4), xlim = c(10 - 3*5, 10 + 3*5))

xcurve = seq(5,15,length =1000)
ycurve = dnorm(xcurve, mean = 10, sd = 4)
polygon(c(5,xcurve,15), c(0,ycurve,0), col = '#d4db0b')

Area = pnorm(15, 10, 4) - pnorm(5, 10, 4)
Area = round(Area, 4)
text(mean(xcurve),max(ycurve)*0.5, paste0('Area= ', Area))

```

# Task 2
```{r}

plain = matrix(1:4, byrow = T, nrow = 2)
template = layout(plain)
layout.show(template)

mean.list = c(10,10,5,5)
sd.list = c(4,2,10,0.5)

for (i in 1:4){
  curve(dnorm(x, mean = mean.list[i], sd = sd.list[i]), xlim = c(mean.list[i] - 3*sd.list[i], mean.list[i] + 3*sd.list[i]))
}

```


$$ Y \sim N(0,1), P(Y \geq 2)$$
```{r}

curve(dnorm(x, mean = 0, sd = 1), xlim = c(0 - 3*1, 0 + 3*1))

xcurve = seq(2,10,length =1000)
ycurve = dnorm(xcurve, mean = 0, sd = 1)
polygon(c(2,xcurve,10), c(0,ycurve,0), col = '#4cbded')

Area = 1 - pnorm(2, 0, 1)
Area = round(Area, 4)
text(2.5,0.02, paste0('Area= ', Area))

```


$$ Y \sim N(\mu = 4, \sigma = 2), P(1 \leq y < 5) $$

```{r}

curve(dnorm(x, mean = 4, sd = 2), xlim = c(4 - 3*2, 4 + 3*2))

xcurve = seq(1,5,length =1000)
ycurve = dnorm(xcurve, mean = 4, sd = 2)
polygon(c(1,xcurve,5), c(0,ycurve,0), col = '#4cbded')

Area = pnorm(5, 4, 2) - pnorm(1, 4, 2)
Area = round(Area, 4)
text(3,0.1, paste0('Area= ', Area))

```

$$ Y \sim N(\mu = 10, \sigma = 4), P(Y < 10)$$
```{r}

curve(dnorm(x, mean = 10, sd = 4), xlim = c(10 - 3*4, 10 + 3*4))

xcurve = seq(-100,10,length =1000)
ycurve = dnorm(xcurve, mean = 10, sd = 4)
polygon(c(-100,xcurve,10), c(0,ycurve,0), col = '#4cbded')

Area = pnorm(10, 10, 4) #- pnorm(1, 4, 2)
Area = round(Area, 4)
text(7,0.04, paste0('Area= ', Area))

```

$$ Y \sim N(\mu = -2, \sigma = 0.5), P(-3 < Y \leq -2) $$

```{r}

curve(dnorm(x, mean = -2, sd = 0.5), xlim = c(-2 - 3*0.5, -2 + 3*0.5))

xcurve = seq(-3,-2,length =1000)
ycurve = dnorm(xcurve, mean = -2, sd = 0.5)
polygon(c(-3,xcurve,-2), c(0,ycurve,0), col = '#4cbded')

Area = abs(pnorm(-3, -2, 0.5) - pnorm(-2, -2, 0.5))
Area = round(Area, 4)
text(-2.5,0.2, paste0('Area= ', Area))

```

# Task 3
```{r}

shape.list = c(1, 3, 5)
scale.list = c(1,1,1)

add = FALSE
color.sel = c('red','blue','green')

for ( i in 1:3){
  
  if (i != 1){
    add = TRUE
  }
  
  curve(dgamma(x, shape = shape.list[i], scale = scale.list[i]), xlim = c(0,6), add = add, col = color.sel[i], lwd = 3)
  
}

```

$$ Y \sim Gamma(shape = 3, scale = 2), P(2 < Y < 5) $$
```{r}

curve(dgamma(x, shape = 3, scale = 2), xlim = c(0,6), lwd = 3)

xcurve = seq(2,5,length =1000)
ycurve = dgamma(xcurve, shape = 3, scale = 2)
polygon(c(2,xcurve,5), c(0,ycurve,0), col = '#4cbded')

Area = pgamma(5, shape = 3, scale = 2) - pgamma(2, shape = 3, scale = 2)
Area = round(Area, 4)
text(3.5,0.06, paste0('Area= ', Area))

```

$$ Y \sim Gamma(shape = 6, scale = 3), P(1 \leq Y \leq 4)$$

```{r}

curve(dgamma(x, shape = 6, scale = 3), xlim = c(0,5), lwd = 3)

xcurve = seq(1,4,length =1000)
ycurve = dgamma(xcurve, shape = 6, scale = 3)
polygon(c(1,xcurve,4), c(0,ycurve,0), col = '#4cbded')

Area = pgamma(4, shape = 6, scale = 3) - pgamma(1, shape = 6, scale = 3)
Area = round(Area, 4)
text(3.5,0.0005, paste0('Area= ', Area))

```

$$ Y \sim Gamma(shape = 2, scale = 4), P(3 \leq Y , 6) $$
```{r}

curve(dgamma(x, shape = 2, scale = 4), xlim = c(0,8), lwd = 3)

xcurve = seq(3,6,length =1000)
ycurve = dgamma(xcurve, shape =2, scale = 4)
polygon(c(3,xcurve,6), c(0,ycurve,0), col = '#4cbded')

Area = pgamma(6, shape = 2, scale = 4) - pgamma(3, shape = 2, scale = 4)
Area = round(Area, 4)
text(4.5,0.04, paste0('Area= ', Area))

```

# Task 4
```{r}

deg.free = c(1,2,4,20)

gri = matrix(1:4, nrow = 2, byrow = T)
layout(gri)

for (i in 1:4){
  curve(dgamma(x, shape = deg.free[i]/2, scale = 2), xlim = c(0,10))
}

```

$$ Y \sim chisq(df = 2),P(2 \leq Y \leq 4) $$
```{r}

curve(dgamma(x, shape = (2/2), scale = 2), xlim = c(0,8), lwd = 3)

xcurve = seq(2,4,length =1000)
ycurve = dgamma(xcurve, shape =(2/2), scale = 2)
polygon(c(2,xcurve,4), c(0,ycurve,0), col = '#4cbded')

Area = pgamma(4, shape = (2/2), scale = 2) - pgamma(2, shape = (2/2), scale = 2)
Area = round(Area, 4)
text(3,0.05, paste0('Area= ', Area))

```

$$ Y \sim chisq(df = 3),P(3 \leq Y \leq5) $$
```{r}

curve(dgamma(x, shape = (3/2), scale = 2), xlim = c(0,8), lwd = 3)

xcurve = seq(3,5,length =1000)
ycurve = dgamma(xcurve, shape =(3/2), scale = 2)
polygon(c(3,xcurve,5), c(0,ycurve,0), col = '#4cbded')

Area = pgamma(5, shape = (3/2), scale = 2) - pgamma(3, shape = (3/2), scale = 2)
Area = round(Area, 4)
text(4,0.05, paste0('Area= ', Area))

```

$$ Y \sim chisq(df = 20), P(10 < Y \leq 21) $$
```{r}

curve(dgamma(x, shape = (20/2), scale = 2), xlim = c(0,25), lwd = 3)

xcurve = seq(10,21,length =1000)
ycurve = dgamma(xcurve, shape =(20/2), scale = 2)
polygon(c(10,xcurve,21), c(0,ycurve,0), col = '#4cbded')

Area = pgamma(21, shape = (20/2), scale = 2) - pgamma(10, shape = (20/2), scale = 2)
Area = round(Area, 4)
text(15,0.02, paste0('Area= ', Area))
```

# Task 5
```{r}

layout(gri)

shape.list5 = c(2,3,4,4)
scale.list5 = c(1,1,1,2)

for (i in  1:4){
  curve(dweibull(x, shape = shape.list5[i], scale = scale.list5[i]), ylim = c(0,2), xlim = c(0,5))
}

```

$$ Y \sim Weibull(shape = 5, scale = 4), P(2 < Y < 3) $$

```{r}

curve(dweibull(x, shape = 5, scale = 4), ylim = c(0,0.8), xlim = c(1,6))
xcurve = seq(2,3,length =1000)
ycurve = dweibull(xcurve, shape =5, scale = 4)
polygon(c(2,xcurve,3), c(0,ycurve,0), col = '#4cbded')

Area = pweibull(3, shape = 5, scale = 4) - pweibull(2, shape = 5, scale = 4)
Area = round(Area, 4)
text(2.5,0.07, paste0('Area= ', Area))

```

$$ Y \sim Weibull(shape = 5, scale = 2), P(2 < Y < 3) $$

```{r}

curve(dweibull(x, shape = 5, scale = 2), ylim = c(0, 1), xlim = c(0,5))
xcurve = seq(2,3,length =1000)
ycurve = dweibull(xcurve, shape =5, scale = 2)
polygon(c(2,xcurve,3), c(0,ycurve,0), col = '#4cbded')

Area = pweibull(3, shape = 5, scale = 2) - pweibull(2, shape = 5, scale = 2)
Area = round(Area, 4)
text(2.5,0.07, paste0('Area= ', Area))

```

$$ Y \sim Weibull(shape = 3, scale = 2), P(2 < Y < 3) $$

```{r}

curve(dweibull(x, shape = 3, scale = 2), ylim = c(0, 1), xlim = c(0,5))
xcurve = seq(2,3,length =1000)
ycurve = dweibull(xcurve, shape =3, scale = 2)
polygon(c(2,xcurve,3), c(0,ycurve,0), col = '#4cbded')

Area = pweibull(3, shape = 3, scale = 2) - pweibull(2, shape = 3, scale = 2)
Area = round(Area, 4)
text(2.5,0.07, paste0('Area= ', Area))

```

# Task 6
```{r}

layout(gri)

beta.list = c(2,3,4,4)
alpha.list = c(2,2,4,5)

# The beta has two shape parameters and one non-centrality paramater 'ncp'
for (i in 1:4){
  curve(dbeta(x, beta.list[i],alpha.list[i]), xlim = c(0,1))
}

```

$$ Y \sim beta(4,2), P(0.4 < Y < 0.5)  $$
```{r}

curve(dbeta(x, 4,2), ylim = c(0, 3))
xcurve = seq(0.4,0.5,length =1000)
ycurve = dbeta(xcurve, 4,2)
polygon(c(0.4,xcurve,0.5), c(0,ycurve,0), col = '#4cbded')


Area = pbeta(0.5, 4,2) - pbeta(0.4, 4,2)
Area = round(Area, 4)
text(0.43,0.5, paste0('Area= ', Area))

```

$$ Y \sim beta(5,3), P(0.2 \leq Y < 0.4) $$

```{r}

curve(dbeta(x, 5,3), ylim = c(0, 3))
xcurve = seq(0.2,0.4,length =1000)
ycurve = dbeta(xcurve, 5,3)
polygon(c(0.2,xcurve,0.4), c(0,ycurve,0), col = '#4cbded')


Area = pbeta(0.4, 5,3) - pbeta(0.2, 5,3)
Area = round(Area, 4)
text(0.3,0.1, paste0('Area= ', Area))

```

$$ Y \sim beta(2,2), P(0.7 \leq Y < 0.8) $$

```{r}

curve(dbeta(x, 2,2), ylim = c(0, 2))
xcurve = seq(0.7,0.8,length =1000)
ycurve = dbeta(xcurve, 2,2)
polygon(c(0.7,xcurve,0.8), c(0,ycurve,0), col = '#4cbded')

Area = pbeta(0.8, 2,2) - pbeta(0.7, 2,2)
Area = round(Area, 4)
text(0.75,0.1, paste0('Area= ', Area))

```

# Task 7

```{r}

myncurve = function(mu, sigma, x){
  curve(dnorm(x,mean=mu,sd=sigma), xlim = c(mu-3*sigma, mu + 3*sigma))
  lowlim = x - 2000
  xcurve = seq(lowlim,x,length =10000)
  ycurve = dnorm(xcurve, mu,sigma)
  
  polygon(c(lowlim,xcurve,x), c(0,ycurve,0), col = '#4cbded')

  Area = pnorm(x, mu,sigma) 
  Area = round(Area, 4)
  text(x-0.5,0.05, paste0('Area= ', Area))
  
}

myncurve(10,1,11)

```

```{r}

library(math4753)

myncurvelab6(10,5,6)

```



